#server configuration
server:
  port: 8081

#spring configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/admindb
    username: postgres
    password: psql
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
